s   = tf('s');
a   = 2;
K   = 1;
tau = .01;
G   = K * exp(-tau * s)/(s * (s^2 + s + a));
nyquist(G);
print('../../Figure/Q3/MATLAB-Nyquist_stable','-dpng','-r400');
a   = 1;
K   = 2;
G   = K * exp(-tau * s)/(s * (s^2 + s + a));
nyquist(G);
print('../../Figure/Q3/MATLAB-Nyquist_unstable','-dpng','-r400');
a   = 1;
K   = 1;
tau = 2;
G   = K * exp(-tau * s)/(s * (s^2 + s + a));
nyquist(G);
print('../../Figure/Q3/MATLAB-Nyquist_increase_tau','-dpng','-r400');
a   = 2;
G   = K * exp(-tau * s)/(s * (s^2 + s + a));
nyquist(G);
print('../../Figure/Q3/MATLAB-Nyquist_increase_tau_and_a','-dpng','-r400');
tau = 100;
G   = K * exp(-tau * s)/(s * (s^2 + s + a));
nyquist(G);
print('../../Figure/Q3/MATLAB-Nyquist_increase_tau_very_lage','-dpng','-r400');
K   = 1e-5;
G   = K * exp(-tau * s)/(s * (s^2 + s + a));
nyquist(G);
print('../../Figure/Q3/MATLAB-Nyquist_increase_tau_very_lage_K_very_low','-dpng','-r400');